function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		local buttons_to_level = {
			["level-1"] = 1,
			["level-2"] = 2,
			["level-3"] = 3,
			["level-4"] = 4,
		}
		for button_name, level in pairs(buttons_to_level) do
			if gui.pick_node(gui.get_node(button_name), action.x, action.y) then
				msg.post("main:/main", "start_game", { level = level })
				break
			end
		end
	end
end